// apps/demo-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import '@material/mwc-button';
import '@clear/ui-component-library';

@Component({
  selector: 'clear-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  public title = 'demo-app';
  public name = 'World';

  public ngOnInit(): void {
    setTimeout(() => {
      this.name = 'Arthur';
    }, 3000);
  }

  public alertMe(event: any) {
    console.log('alert!!!', event);
  }
}

<div style="text-align:center">
  <h1>
    Welcome to <span>{{ title }}</span
    >!
  </h1>

  <uicom-hello [who]="name" (my-event)="alertMe($event)"></uicom-hello>

  <mwc-button unelevated="" label="Click me!" icon="check"></mwc-button>
</div>

<router-outlet></router-outlet>

// apps/demo-react-app/src/app/app.tsx
import React, { RefObject } from 'react';

import '@material/mwc-button';
import '@clear/ui-component-library';

import './app.scss';

export class App extends React.Component<{}, { person: string }> {
  public helloComponntRef: RefObject<any>;

  constructor(props) {
    super(props);

    this.state = { person: 'World' };
    this.helloComponntRef = React.createRef();
  }

  public componentDidMount(): void {
    this.helloComponntRef.current.addEventListener(
      'my-event',
      this.alertMe.bind(this)
    );

    setTimeout(() => {
      this.setState({ person: 'Arthur' });
    }, 2000);
  }

  public render() {
    return (
      <div>
        <header style={{ textAlign: 'center' }}>
          <h1>
            Welcome to <span>demo-react-app!</span>
          </h1>

          <uicom-hello
            who={this.state.person}
            onMyEvent={this.alertMe}
            ref={this.helloComponntRef}
          />

          <mwc-button unelevated="" label="Click me!" icon="check" />
        </header>
      </div>
    );
  }

  public alertMe(event) {
    console.log('alert!!!', event);
  }
}

export default App;
